### ISSUE TITLE
Support for Nuxtjs

### ISSUE THREAD

**Issue by davorpeic** [icehaunter/vue3-datepicker#37]
Hi,

I'm fighting to get this working with NuxtJs (2.15) but getting errors like

```
 ERROR  9:31:46 AM [vite] error while updating dependencies:                                       09:31:46
Error: Build failed with 24 errors:
node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js:1:9: error: No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "defineComponent"
node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js:1:26: error: No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "pushScopeId"
node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js:1:39: error: No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "popScopeId"
node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js:1:51: error: No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "openBlock"
node_modules/vue3-datepicker/dist/vue3-datepicker.esm.js:1:62: error: No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "createBlock"
...
    at failureErrorWithLog (/ProjectPath/node_modules/esbuild/lib/main.js:1224:15)
    at buildResponseToResult (/ProjectPath/node_modules/esbuild/lib/main.js:936:32)
    at /ProjectPath/node_modules/esbuild/lib/main.js:1035:20
    at /ProjectPath/node_modules/esbuild/lib/main.js:568:9
    at handleIncomingPacket (/ProjectPath/node_modules/esbuild/lib/main.js:657:9)
    at Socket.readFromStdout (/ProjectPath/node_modules/esbuild/lib/main.js:535:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

I tried to setup plugin per nuxt plugin documentation but with no luck. Any ideas?
Thanks

**Comment by davorpeic** [comment]
Just un update, the issue is related with NuxtJs not supporting vue3 yet..
